version: 2
updates:
    - package-ecosystem: github-actions
      directory: /
      schedule:
          interval: monthly
          day: monday
      groups:
          all:
              patterns:
                  - '*'

    - package-ecosystem: npm
      directory: /
      schedule:
          interval: monthly
          day: monday
      ignore:
          - dependency-name: '@types/node'
            update-types:
                - 'version-update:semver-major'
      groups:
          all:
              patterns:
                  - '*'
