# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2011-2020 ETH Zurich.

name: 'check-license-header'
description: 'GitHub action to check whether all files have a specified copyright license header'
inputs:
    path:
        description: 'Path to working directory'
        required: true
    config:
        description: 'Path to JSON config file'
        required: true
    strict:
        description: 'Specifies whether files not covered by the configuration should be treated as errors'
        required: false
        default: false
runs:
    using: 'node20'
    main: 'dist/main/index.js'
branding:
    icon: 'check'
    color: 'gray-dark'
