# The MIT License (MIT)

# Copyright (c) 2018 GitHub, Inc. and contributors

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

name: 'build-test'
on: # rebuild any PRs and main branch changes
    pull_request:
    push:

jobs:
    build: # make sure build/ci work properly
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version-file: .node-version
                  cache: npm
            - run: npm ci --cache .npm --prefer-offline
            - run: npm run all
    test: # make sure the action works on a clean machine without building
        if: contains(github.ref, 'refs/heads/releases/')
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: ./
              with:
                  path: ./
                  config: ./.github/license-check/license-config.json
                  strict: true
